server:
  port: 8082
spring:
  application:
    name: "weather-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri:  ${MONGO_URL}
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    virtual_host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 0
visualcrossing:
  url: "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
  key: ${VISUAL_KEY}
process:
  concurrency: "1-1"
  type: "ACK" #"ACK-Manual, ACK-Auto, ACK-Manual-And-Concurrency, ACK-Manual-And-Prefetch, ACK-Auto-And-Concurrency, ACK-Auto-And-Prefetch"
