server:
  port: 8082
spring:
  application:
    name: "weather-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri:  ${MONGO_URL}
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    virtual_host: /
visualcrossing:
  url: "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
  key: ${VISUAL_KEY}
