##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: IntegrationPatterns
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

visualcrossing:
  url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/
  key: 46URCCVEEGS7DWZVRU7ML9FK2
